name: run
on: workflow_dispatch
jobs:
 b:
  runs-on: ubuntu-latest
  permissions: {contents: write}
  steps:
   - uses: actions/checkout@v4
   - run: pip install requests
   - run: python go.py
   - run: git config user.email a@b.c; git config user.name a; git add out.json; git commit -m out; git push
